### ISSUE TITLE
Right click works in primary window, but not child windows

### ISSUE THREAD

**Issue by grantthomas** [MagiusCHE/prospect-mail#10]
Right clicking works in the compose message body of the main window.
However, if I double-click a message and reply in the child popup, right click does not function.

https://user-images.githubusercontent.com/21267386/153252559-acaeee05-7d01-4303-801f-aec3160281a8.mp4

**Comment by MagiusCHE** [comment]
Fix published on https://github.com/MagiusCHE/prospect-mail/releases/tag/v0.5.1-beta-tmp

**Comment by grantthomas** [comment]
Works for me on initial testing.

Thanks you **very** much for such rapid corrections.
